export const TYPE_FIELD_TEXT = "TYPE_FIELD_TEXT";
export const TYPE_FIELD_SELECT = "TYPE_FIELD_SELECT";
export const TYPE_FIELD_DATETIME = "TYPE_FIELD_DATETIME";
export const TYPE_FIELD_DATE = "TYPE_FIELD_DATE";
export const TYPE_FIELD_CUSTOM = "TYPE_FIELD_CUSTOM";
export const TYPE_FIELD_AUTOCOMPLETE = "TYPE_FIELD_AUTOCOMPLETE";
export const TYPE_FIELD_NUMBER = "TYPE_FIELD_NUMBER";
export const TYPE_FIELD_SELECT_MULTIPLE = "TYPE_FIELD_SELECT_MULTIPLE";
