export const FORM_ADD_FIELD = "FORM_ADD_FIELD";
export const FORM_ADD_FIELD_FAILED = "FORM_ADD_FIELD_FAILED";
export const FORM_VALUE_UPDATE = "FORM_VALUE_UPDATE";
export const FORM_VALUE = "FORM_VALUE";
export const FORM_RESET_FIELD = "FORM_RESET_FIELD";
