import { menuAccess } from "./_access";
import { Icon } from "@iconify-icon/react";
import { NavigationState } from "app/store/reducers/fuse/navigation.reducer";

export const adminMenu: NavigationState[] = [
  {
    id: "main-navigation",
    title: "Menu Utama",
    type: "group",
    children: [
      {
        id: "summary_dashboard",
        title: "Dashboard",
        type: "item",
        icon: "dashboard",
        url: "/my_dashboard/summary",
      },
      {
        id: "users_n_groups",
        title: "Users & Groups",
        type: "collapse",
        icon: "vpn_key",
        children: [
          {
            id: "users",
            title: "Admin",
            type: "item",
            icon: <Icon icon="mdi:account-security" />,
            url: "/users_n_groups/users",
            access: menuAccess("users"),
          },
          {
            id: "organizations",
            title: "Perusahaan",
            type: "item",
            icon: <Icon icon="octicon:organization-16" />,
            url: "/users_n_groups/organizations",
            access: menuAccess("organizations", { edit: true }),
          },
          // {
          //   id: "settings",
          //   title: "Pengaturan",
          //   type: "item",
          //   icon: <Icon icon="mdi:wrench" />,
          //   url: "/users_n_groups/setting",
          // },
        ],
      },
      {
        id: "master",
        title: "Master",
        type: "collapse",
        icon: "settings",
        children: [
          {
            id: "areas",
            title: "Area",
            type: "item",
            icon: <Icon icon="mdi:office-building" />,
            url: "/master/areas",
            access: menuAccess("areas"),
          },
          {
            id: "departments",
            title: "Departemen",
            type: "item",
            icon: <Icon icon="fluent:people-team-20-filled" />,
            url: "/master/departments",
            access: menuAccess("departments"),
          },
          {
            id: "positions",
            title: "Jabatan",
            type: "item",
            icon: <Icon icon="mdi:briefcase" />,
            url: "/master/positions",
            access: menuAccess("positions"),
          },
          {
            id: "leaveTypes",
            title: "Jenis Cuti",
            type: "item",
            icon: <Icon icon="mdi:user-arrow-right-outline" />,
            url: "/master/leaveTypes",
            access: menuAccess("leaveTypes"),
          },
          {
            id: "trainingTypes",
            title: "Jenis Latihan",
            type: "item",
            icon: <Icon icon="healthicons:i-training-class" />,
            url: "/master/trainingTypes",
            access: menuAccess("trainingTypes"),
          },
          {
            id: "employees",
            title: "Karyawan",
            type: "item",
            icon: <Icon icon="mdi:user" />,
            url: "/master/employees",
            access: menuAccess("employees"),
          },
          {
            auth: ["admin"],
            id: "organizations",
            title: "Perusahaan",
            type: "item",
            icon: <Icon icon="octicon:organization-16" />,
            url: "/master/organizations",
            access: menuAccess("organizations"),
          },
        ],
      },
      {
        id: "device_list",
        title: "Perangkat",
        type: "item",
        icon: <Icon icon="mdi:fingerprint" />,
        url: "/devices/device_list",
        access: menuAccess("device_list"),
      },
      {
        id: "approval",
        title: "Persetujuan",
        type: "collapse",
        icon: "fact_check",
        children: [
          {
            id: "leave",
            title: "Cuti",
            type: "item",
            icon: <Icon icon="mdi:user-arrow-right-outline" />,
            url: "/approval/leave",
            access: menuAccess("leave", { edit: true, delete: true }),
          },
          {
            id: "training",
            title: "Pelatihan",
            type: "item",
            icon: <Icon icon="healthicons:i-training-class" />,
            url: "/approval/training",
            access: menuAccess("training", { edit: true, delete: true }),
          },
          {
            id: "overtime",
            title: "Lembur",
            type: "item",
            icon: <Icon icon="material-symbols:more-time-rounded" />,
            url: "/approval/overtime",
            access: menuAccess("overtime", { edit: true, delete: true }),
          },
          {
            id: "manual_log",
            title: "Catatan Manual",
            type: "item",
            icon: <Icon icon="mdi:pen" />,
            url: "/approval/manual_log",
            access: menuAccess("manual_log", { edit: true, delete: true }),
          },
          {
            id: "approval_shift",
            title: "Ganti Shift",
            type: "item",
            icon: <Icon icon="material-symbols:change-circle" />,
            url: "/approval/approval_shift",
            access: menuAccess("approval_shift", { edit: true, delete: true }),
          },
        ],
      },
      {
        id: "holiday",
        title: "Libur",
        type: "item",
        icon: <Icon icon="fontisto:holiday-village" />,
        url: "/holidays/holiday",
        access: menuAccess("holiday"),
      },
      {
        id: "shifts",
        title: "Shift",
        type: "collapse",
        icon: <Icon icon="mdi:calendar-multiple" />,
        children: [
          {
            id: "time_table",
            title: "Jadwal",
            type: "item",
            icon: "schedule",
            url: "/shifts/time_table",
            access: menuAccess("time_table"),
          },
          {
            id: "shift",
            title: "Shift",
            type: "item",
            icon: <Icon icon="mdi:calendar-multiple" />,
            url: "/shifts/shift",
            access: menuAccess("shift"),
          },
        ],
      },
      {
        id: "roster_management",
        title: "Roster Management",
        type: "collapse",
        icon: <Icon icon="mdi:person-clock" />,
        children: [
          {
            id: "roster",
            title: "Roster",
            type: "item",
            icon: <Icon icon="mdi:person-clock" />,
            url: "/roster_management/roster",
            access: menuAccess("roster"),
          },
          {
            id: "process",
            title: "Process",
            type: "item",
            icon: <Icon icon="mdi:gear" />,
            url: "/roster_management/process",
            access: menuAccess("process"),
          },
        ],
      },
      {
        id: "workflow",
        title: "Workflow",
        type: "collapse",
        icon: "work",
        children: [
          {
            id: "workflowRole",
            title: "Workflow Role",
            type: "item",
            icon: <Icon icon="mdi:shield-user" />,
            url: "/workflow/workflowRole",
            access: menuAccess("workflowRole"),
          },
          {
            id: "workflowBuilder",
            title: "Workflow Builder",
            type: "item",
            icon: <Icon icon="mdi:wrench" />,
            url: "/workflow/workflowBuilder",
            access: menuAccess("workflowBuilder"),
          },
          {
            id: "workflowNode",
            title: "Workflow Node",
            type: "item",
            icon: <Icon icon="mdi:file-tree" />,
            url: "/workflow/workflowNode",
            access: menuAccess("workflowNode", { edit: true }),
          },
        ],
      },
      {
        id: "transaction_report",
        title: "Laporan",
        type: "collapse",
        icon: <Icon icon="mdi:chart-box" />,
        children: [
          {
            id: "transaction",
            title: "Kehadiran - Perangkat",
            type: "item",
            icon: <Icon icon="mdi:fingerprint" />,
            url: "/transaction_report/transaction",
          },
          {
            id: "mobile_log",
            title: "Kehadiran - Aplikasi",
            type: "item",
            icon: <Icon icon="mdi:cellphone" />,
            url: "/transaction_report/mobile_log",
          },
          {
            id: "attendance_report",
            title: "Kehadiran",
            type: "item",
            icon: <Icon icon="mdi:calendar-user" />,
            url: "/transaction_report/attendance_report",
          },
          {
            id: "recapitulation_report",
            title: "Rekapitulasi",
            type: "item",
            icon: <Icon icon="ph:table" />,
            url: "/transaction_report/recapitulation_report",
          },
          {
            id: "in_out_report",
            title: "In Out",
            type: "item",
            icon: <Icon icon="mdi:stopwatch" />,
            url: "/transaction_report/in_out_report",
          },
          {
            id: "status_report",
            title: "Status",
            type: "item",
            icon: <Icon icon="material-symbols:calendar-view-day" />,
            url: "/transaction_report/status_report",
          },
          {
            id: "roster_report",
            title: "Roster",
            type: "item",
            icon: <Icon icon="mdi:person-clock" />,
            url: "/transaction_report/roster_report",
          },
        ],
      },
      // {
      //   id: "payroll",
      //   title: "Payroll",
      //   type: "collapse",
      //   icon: <Icon icon="fluent:people-money-24-filled" />,
      //   children: [
      //     {
      //       id: "payroll_component",
      //       title: "Komponen Payroll",
      //       type: "item",
      //       icon: <Icon icon="fluent-mdl2:web-components" />,
      //       url: "/payroll/component",
      //     },
      //     {
      //       id: "payroll_template",
      //       title: "Template Payroll",
      //       type: "item",
      //       icon: <Icon icon="mdi:file" />,
      //       url: "/payroll/template",
      //     },
      //     {
      //       id: "payroll_create",
      //       title: "Buat Payroll",
      //       type: "item",
      //       icon: <Icon icon="fluent:money-hand-24-filled" />,
      //       url: "/payroll/create",
      //     },
      //     {
      //       id: "payroll_master",
      //       title: "Payroll Master",
      //       type: "item",
      //       icon: <Icon icon="solar:money-bag-bold" />,
      //       url: "/payroll/master",
      //     },
      //     {
      //       id: "payroll_report",
      //       title: "Laporan",
      //       type: "item",
      //       icon: <Icon icon="mdi:chart-box" />,
      //       url: "/payroll/report",
      //     },
      //     // {
      //     //   id: "payroll_ex_employee_allowance",
      //     //   title: "Pesangon Mantan Kry",
      //     //   type: "item",
      //     //   icon: <Icon icon="mdi:person-arrow-right-outline" />,
      //     //   url: "/payroll/ex-employee-allowance",
      //     // },
      //     // {
      //     //   id: "payroll_thr",
      //     //   title: "THR",
      //     //   type: "item",
      //     //   icon: <Icon icon="mingcute:diamond-fill" color="lime" />,
      //     //   url: "/payroll/thr",
      //     // },
      //     // {
      //     //   id: "payroll_salary_tax_calculator",
      //     //   title: "Kalkulator Pajak Gaji",
      //     //   type: "item",
      //     //   icon: <Icon icon="mdi:calculator"/>,
      //     //   url: "/payroll/salary-tax-calculator",
      //     // },
      //     // {
      //     //   id: "payroll_export",
      //     //   title: "Export",
      //     //   type: "item",
      //     //   icon: <Icon icon="mdi:file-export"/>,
      //     //   url: "/payroll/export",
      //     // },
      //     // {
      //     //   id: "payroll_import",
      //     //   title: "Import",
      //     //   type: "item",
      //     //   icon: <Icon icon="mdi:file-import"/>,
      //     //   url: "/payroll/import",
      //     // },
      //   ],
      // },
      // {
      //   id: "geofence",
      //   title: "Geo Fence",
      //   type: "collapse",
      //   icon: <Icon icon="mdi:fence"/>,
      //   children: [
      //     {
      //       id: "geofence_location",
      //       title: "Lokasi",
      //       type: "item",
      //       icon: "location_on",
      //       url: "/geofence/location",
      //     },
      //     {
      //       id: "geofence_rules",
      //       title: "Rules",
      //       type: "item",
      //       icon: <Icon icon="mdi:lock"/>,
      //       url: "/geofence/rules",
      //     },
      //   ],
      // },
      // {
      //   id: "external_api",
      //   title: "External API",
      //   type: "item",
      //   icon: <Icon icon="mdi:api"/>,
      //   url: "/external_api",
      // },
      {
        id: "import",
        title: "Import",
        type: "item",
        icon: <Icon icon="mdi:import" />,
        url: "/import",
      },
    ],
  },
];
