import { GeneralConfigField } from "@/interface";

export const FieldData: GeneralConfigField[] = [
  {
    type: "select",
    name: "type",
    label: "Tipe Cuti",
    placeholder: "",
    search: true,
    option: null,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: "",
    type: "text",
    name: "reason",
    label: "Alasan",
    placeholder: "",
    search: true,
    multiline: false,
    required: false,
  },
  {
    value: "",
    type: "date",
    name: "startDate",
    label: "Tanggal Mulai",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa Tanggal",
    },
    required: true,
  },
  {
    value: "",
    type: "date",
    name: "endDate",
    label: "Tanggal Selesai",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa Tanggal",
    },
    required: true,
  },
  {
    value: "",
    type: "select",
    name: "auditStatus",
    label: "Status",
    placeholder: "",
    search: true,
    option: [
      { label: "Pending", value: "Pending" },
      { label: "Approved", value: "Approved" },
      { label: "Rejected", value: "Rejected" },
    ],
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: "",
    type: "text",
    name: "auditRemark",
    label: "Catatan Persetujuan",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    required: false,
  },
];
