import { GeneralConfigField } from "interface";

export const FieldData: GeneralConfigField[] = [
  {
    value: "",
    type: "text",
    name: "breakTimeName",
    label: "Nama",
    placeholder: "",
    search: true,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: 0,
    type: "select",
    name: "calculateType",
    label: "Tipe Penghitungan",
    placeholder: "",
    search: false,
    option: [{ label: "Kurangi Otomatis", value: 1 }],
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: "12:00:00",
    type: "time",
    name: "startTime",
    label: "Waktu Mulai",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: "13:00:00",
    type: "time",
    name: "endTime",
    label: "Waktu Akhir",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
  {
    value: 60,
    type: "number",
    name: "duration",
    label: "Durasi (Menit)",
    placeholder: "",
    search: false,
    multiline: false,
    rows: 0,
    rowsMax: 0,
    validations: "isNumeric",
    validationErrors: {
      isNumeric: "Field Harus diisi dan hanya boleh berupa angka",
    },
    required: true,
  },
  {
    value: null,
    type: "select",
    name: "organizationId",
    label: "Perusahaan",
    placeholder: "",
    search: true,
    option: null,
    validations: "isExisty",
    validationErrors: {
      isExisty: "Field Harus diisi dan hanya boleh berupa kalimat",
    },
    required: true,
  },
];
